trigger:
  - '*'

pool:
  vmImage: ubuntu-latest

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
    displayName: 'SetUp Java'

  - script: |
      ./mvnw verify -DforkCount=4
    displayName: 'Build with Maven'
