version: '2.1'
orbs:
  maven: circleci/maven@1.3.0
executors:
  machine_executor_amd64:
    machine:
      image: ubuntu-2204:2022.04.2
    environment:
      architecture: "amd64"
      platform: "linux/amd64"
workflows:
  maven_test:
    jobs:
      - maven/parallel_test:
          executor: machine_executor_amd64
          parallelism: 4
          parallel_it_pattern: "**/*Test*.java"
