name: CI Build

on:
  push:
    branches:
      - '**'
jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: prepull
        run: |
          docker pull -q postgres:15-alpine &
          docker pull -q mongo:4.2 &
          docker pull -q confluentinc/cp-kafka:7.2.1 &
          docker pull -q redis:7.0.5-alpine &
          docker pull -q jamesdbloom/mockserver:mockserver-5.13.2 &
          docker pull -q docker.redpanda.com/vectorized/redpanda:v22.2.1 &
          docker pull -q testcontainers/ryuk:0.3.4 &

      - name: Build with Maven
        run: ./mvnw verify

      - name: Store JFR recordings
        uses: actions/upload-artifact@v3
        with:
          name: jfr-recordings
          retention-days: 5
          path: |
            recording-*.jfr
            beep.txt

