name: CI Build

on:
  push:
    branches:
      - '**'
jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup Testcontainers Cloud
        uses: atomicjar/testcontainers-cloud-setup-action@main
        env:
         TC_CLOUD_TOKEN: ${{ secrets.TC_CLOUD_TOKEN }}
         TC_CLOUD_CONCURRENCY: 2

      - name: Build with Maven
        run: ./mvnw -DforkCount=4 verify

      - name: Store JFR recordings
        uses: actions/upload-artifact@v3
        with:
          name: jfr-recordings
          retention-days: 5
          path: |
            recording-*.jfr

